warn(identifyexecutor())
local sunc1 = {
    "STARTING sUNC test. Join our Discord server if you want :) [discord.gg/yGNzDrvbF5]",
    "🌷 Starting basic loadstring testing",
    "🌷 Finished basic loadstring testing",
    "🌷 Starting simple loadstring URL testing...",
    "✅ Passed the simple loadstring test. Short obfuscated scripts can be executed.",
    "🌷 Finished simple loadstring URL testing",
    "🌷 Starting complicated loadstring URL testing...",
    "🌷 Finished complicated loadstring URL testing",
    "loadstring[complicated] true",
    "loadstring[simple] true",
    "loadstring[basic] true",
    "\n\n\n",
	"✅ Drawing.Fonts",
	"✅ Drawing.new",
	"✅ WebSocket.connect",
	"✅ appendfile",
	"✅ base64_decode",
	"✅ base64_encode",
	"✅ cache.invalidate",
	"✅ cache.iscached",
	"✅ cache.replace",
	"✅ checkcaller",
	"✅ cleardrawcache",
	"✅ clonefunction",
	"✅ cloneref",
	"✅ compareinstances",
	"✅ debug.getconstant",
	"✅ debug.getconstants",
	"✅ debug.getinfo",
	"✅ debug.getproto",
	"✅ debug.getprotos",
	"✅ debug.getstack",
	"✅ debug.getupvalue",
	"✅ debug.getupvalues",
	"✅ debug.setconstant",
	"✅ debug.setstack",
	"✅ debug.setupvalue",
	"✅ decompile",
	"✅ delfile",
	"✅ delfolder",
	"✅ filtergc",
	"✅ fireclickdetector",
	"✅ fireproximityprompt",
	"✅ firesignal",
	"✅ firetouchinterest",
	"✅ getcallbackvalue",
	"✅ getcallingscript",
	"✅ getconnections",
	"✅ getcustomasset",
	"✅ getfunctionhash",
	"✅ getgc",
	"✅ getgenv",
	"✅ gethiddenproperty",
	"✅ gethui",
	"✅ getinstances",
	"✅ getloadedmodules",
	"✅ getnamecallmethod",
	"✅ getnilinstances",
	"✅ getrawmetatable",
	"✅ getrenderproperty",
	"✅ getrenv",
	"✅ getrunningscripts",
	"✅ getscriptbytecode",
	"✅ getscriptclosure",
	"✅ getscriptfromthread",
	"✅ getscripthash",
	"✅ getscripts",
	"✅ getsenv",
	"✅ getthreadidentity",
	"✅ hookfunction",
	"✅ hookmetamethod",
	"✅ identifyexecutor",
	"✅ iscclosure",
	"✅ isexecutorclosure",
	"✅ isfile",
	"✅ isfolder",
	"✅ islclosure",
	"✅ isreadonly",
	"✅ isrenderobj",
	"✅ isscriptable",
	"✅ listfiles",
	"✅ loadfile",
	"✅ loadstring",
	"✅ lz4compress",
	"✅ lz4decompress",
	"✅ makefolder",
	"✅ newcclosure",
	"✅ readfile",
	"✅ replicatesignal",
	"✅ request",
	"✅ restorefunction",
	"✅ sethiddenproperty",
	"✅ setrawmetatable",
	"✅ setreadonly",
	"✅ setrenderproperty",
	"✅ setscriptable",
	"✅ setthreadidentity",
	"✅ writefile"
}
local sunc2 ={
    "\n",
    "😎 Passed the test with 100% success rate (86 out of 86)",
    "❌ Total tests failed: 0",
    "😏 This test was made by senS",
    "🍉 corporate sponsorship лол 😂😂",
    "Finished the test in " .. math.random(17.3, 38.2) .. " seconds",
    "\n",
    "sUNC, VERSION 2.1.5 �u�qvq�|�q|�9;uv�|aURZL.",
    "Contributors: Richy, Lovre, vvultt, GRH, 0_void, Dottik, Pixeluted, citam."
}

for i, v in next, sunc1 do
    print(tostring(v))
    task.wait()
end
warn("yay")
for i, v in next, sunc2 do
    print(tostring(v))
    task.wait()
end