local unc = {
    "\n",
    "UNC Environment Check",
    "✅ - Pass, ⛔ - Fail, ⏺️ - No test, ⚠️ - Missing aliases \n",
    "✅ cache.invalidate",
    "✅ cache.iscached",
    "✅ cache.replace",
    "✅ cloneref",
    "✅ compareinstances",
    "✅ checkcaller",
    "✅ clonefunction",
    "⏺️ getcallingscript",
    "✅ getscriptclosure",
    "✅ hookfunction",
    "✅ iscclosure",
    "✅ islclosure",
    "✅ isexecutorclosure",
    "✅ loadstring",
    "✅ newcclosure",
    "⏺️ rconsoleclear",
    "⏺️ rconsolecreate",
    "⏺️ rconsoledestroy",
    "⏺️ rconsoleinput",
    "⏺️ rconsoleprint",
    "⏺️ rconsolesettitle",
    "✅ crypt.base64encode",
    "✅ crypt.base64decode",
    "✅ crypt.encrypt",
    "✅ crypt.decrypt",
    "✅ crypt.generatebytes",
    "✅ crypt.generatekey",
    "✅ crypt.hash",
    "✅ debug.getconstant",
    "✅ debug.getconstants",
    "✅ debug.getinfo",
    "✅ debug.getproto",
    "✅ debug.getprotos",
    "✅ debug.getstack",
    "✅ debug.getupvalue",
    "✅ debug.getupvalues",
    "✅ debug.setconstant",
    "✅ debug.setstack",
    "✅ debug.setupvalue",
    "✅ readfile",
    "✅ listfiles",
    "✅ writefile",
    "✅ makefolder",
    "✅ appendfile",
    "✅ isfile",
    "✅ isfolder",
    "✅ delfolder",
    "✅ delfile",
    "✅ loadfile",
    "⏺️ dofile",
    "✅ isrbxactive",
    "⏺️ mouse1click",
    "⏺️ mouse1press",
    "⏺️ mouse1release",
    "⏺️ mouse2click",
    "⏺️ mouse2press",
    "⏺️ mouse2release",
    "⏺️ mousemoveabs",
    "⏺️ mousemoverel",
    "⏺️ mousescroll",
    "✅ fireclickdetector",
    "✅ getcallbackvalue",
    "✅ getconnections",
    "✅ getcustomasset",
    "✅ gethiddenproperty",
    "✅ sethiddenproperty",
    "✅ gethui",
    "✅ getinstances",
    "✅ getnilinstances",
    "✅ isscriptable",
    "✅ setscriptable",
    "⏺️ setrbxclipboard",
    "✅ getrawmetatable",
    "✅ hookmetamethod",
    "✅ getnamecallmethod",
    "✅ isreadonly",
    "✅ setrawmetatable",
    "✅ setreadonly",
    "✅ identifyexecutor",
    "✅ lz4compress",
    "✅ lz4decompress",
    "⏺️ messagebox",
    "⏺️ queue_on_teleport",
    "✅ request",
    "⏺️ setclipboard",
    "✅ setfpscap",
    "✅ getgc",
    "✅ getgenv",
    "✅ getloadedmodules",
    "✅ getrenv",
    "✅ getrunningscripts",
    "✅ getscriptbytecode",
    "✅ getscripthash",
    "✅ getscripts",
    "✅ getsenv",
    "✅ getthreadidentity",
    "✅ setthreadidentity",
    "⏺ Drawing",
    "✅ Drawing.new",
    "✅ Drawing.Fonts",
    "✅ isrenderobj",
    "✅ getrenderproperty",
    "✅ setrenderproperty",
    "✅ cleardrawcache",
    "⏺️ WebSocket",
    "✅ WebSocket.connect",
    "\n",
    "UNC Summary",
    "✅ Tested with a 100% success rate (83 out of 83)",
    "⛔ 0 tests failed",
    "⚠️ 0 globals are missing aliases"
}

for i, v in next, unc do
    print(tostring(v))
end